baseurl = "https://girbons.me/"
title = "girbons.me"
copyright = "&copy; 2017 Alessandro De Angelis"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

googleAnalytics = "UA-101643580-1"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  name = "Alessandro De Angelis"
  role = "Software Developer"
  organization = "Evonove"
  organization_url = "https://evonove.it"
  gravatar = false
  avatar = "profile.jpeg"

  email = "alessandrodea22@gmail.com"
  highlight = true
  highlight_languages = []
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:alessandrodea22@gmail.com"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/girbons"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/girbons"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/Girbonss"

# Navigation Links
[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 3

[languages.en]
  languageCode = "en-us"
